name: Node.js Package

on:
    release:
        types: [created]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            # Setup .npmrc file to publish to npm
            - uses: actions/setup-node@v3
              with:
                  node-version: "v16.13.2"
                  registry-url: "https://registry.npmjs.org"

            # Publish to npm
            - run: npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

            # Setup .npmrc file to publish to GitHub Packages
            - uses: actions/setup-node@v3
              with:
                  node-version: "v16.13.2"
                  registry-url: "https://npm.pkg.github.com"

            - name: Authenticate with the GitHub Package Registry
              run: echo "//npm.pkg.github.com:_authToken=${{ secrets.GITHUB_TOKEN }}" >
                  ~/.npmrc

            # Publish to GitHub Packages
            - run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
