name: Test suite

on:
    push:
        branches: [main, dev]
    pull_request:
        branches: [main, dev]

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [14, 16, 18]

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Upgrade NPM
              run: npm i -g npm

            - name: Install dependencies
              run: npm ci

            - name: Run tests
              run: npm run test
              env:
                  CI: true
