name: Test Suite

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14, 16, 18]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm run test
      env:
        CI: true

#    - name: Badge
#      uses: js-choi/gh-badge@v1.5.0
#      if: success()
#      with:
#        text: 'Node.js ${{ matrix.node-version }}'
#        color: green
#        icon: check
#        style: flat
